server:
  host: '0.0.0.0'
  port: 18000
logs:
  level: debug
root:
  user: root
  pass: admin123
luck:
  nscan: 0.01 # 1%
training:
  luck-01:
    time: 300 # 5 minutes
    require: ['training:scan-02']
    headline: Basic Probability Theory
    body: |
      Probability quantifies as a number between 0 and 1, where, roughly speaking,
      0 indicates impossibility and 1 indicates certainty. The higher the probability
      of an event, the more likely it is that the event will occur. A simple example
      is the tossing of a fair (unbiased) coin. Since the coin is fair, the two outcomes
      ("heads" and "tails") are both equally probable; the probability of "heads" equals
      the probability of "tails"; and since no other outcomes are possible, the
      probability of either "heads" or "tails" is 1/2
      (which could also be written as 0.5 or 50%).
    reward: |
      {bold Reward:}
        {cyan.green +1 luck}
  luck-02:
    time: 3600 # 1 hour
    require: ['training:luck-01']
    headline: Basic Chaos theory
    body: |
      Chaos theory is a branch of mathematics focusing on the behavior of
      dynamical systems that are highly sensitive to initial conditions. Chaos theory
      is an interdisciplinary theory stating that, within the apparent randomness of
      chaotic complex systems, there are underlying patterns, constant feedback loops,
      repetition, self-similarity, fractals, and self-organization. The butterfly
      effect describes how a small change in one state of a deterministic nonlinear
      system can result in large differences in a later state, meaning there is
      sensitive dependence on initial conditions. A metaphor for this behavior is
      that a butterfly flapping its wings in China can cause a hurricane in Texas.
    reward: |
      {bold Reward:}
        {cyan.green +1 luck}
  scan-01:
    time: 60 # 1 minute
    rewards: ['pkg:nscan']
    headline: nscan
    body: |
      nscan ("Network Scanner") is a free and open source utility for network discovery
      and security auditing. Many systems and network administrators also find it useful
      for tasks such as network inventory, managing service upgrade schedules, and
      monitoring host or service uptime. nscan uses raw IP packets in novel ways to
      determine what hosts are available on the network, what services (application
      name and version) those hosts are offering, what operating systems
      (and OS versions) they are running, what type of packet filters/firewalls are
      in use, and dozens of other characteristics.
    reward: |
      {bold Reward:}
        {cyan.green nscan}
  scan-02:
    time: 300 # 5 minutes
    require: ['training:scan-01']
    headline: Internet of Things Devices
    body: |
      IoT devices, or any of the many things in the internet of things, are
      nonstandard computing devices that connect wirelessly to a network and
      have the ability to transmit data.
    reward: |
      {bold Reward:}
        {cyan.green nscan iot}
  scan-03:
    time: 3600 # 1 hour
    require: ['training:scan-02']
    headline: Home PC
    body: |
      Home PCs connected directly to the internet offer an entrypoint into a
      users home network. Home PCs have a treasure trove of personal information
      that is easily exploitable for profits.
    reward: |
      {bold Reward:}
        {cyan.green nscan pc}
  crypto-01:
    time: 60 # 1 minute
    require: ['training:scan-01']
    rewards: ['pkg:coind', 'pkg:wallet']
    headline: Introduction to Cryptocurrency
    body: |
      A cryptocurrency (or crypto currency) is a digital asset designed to work
      as a medium of exchange that uses strong cryptography to secure financial
      transactions, control the creation of additional units, and verify the
      transfer of assets. Cryptocurrencies use decentralized control as opposed
      to centralized digital currency and central banking systems.
    reward: |
      {bold Reward:}
        {cyan.green coind package}
        {cyan.green wallet package}
  crypto-02:
    time: 300 # 5 minutes
    require: ['training:crypto-01', 'training:scan-03']
    rewards: ['pkg:cryptolock']
    headline: Applied Cryptography
    body: |
      Cryptography is present in everyday life, from paying with a credit card
      to using the telephone. Learn all about making and breaking puzzles
      in computing.

      {bold Reward:}
        {cyan.green cryptolock package}
copy:
  welcome-text: |
    Welcome to Terminal v{VERSION}

    All connections are monitored and recorded
    Disconnect IMMEDIATELY if you are not authorized!

    Your Address has been logged: {ADDRESS}
  invalid-session: 'Error: Invalid Session, please login again.'
mail:
  welcome:
    text: |
      Congratulations!

      You can follow simple instructions. I had my doubts.

      You must prove to us you are capable, trustworty, and above all else, loyal.

      But right now you don't know shit.

      So learn a few things and maybe we'll be in contact again.

      - X
    tasks:
      - { train: scan-01 }
  trained:
    text: |
      You are a quick learner. But learning and doing are two separate things.

      Use {cyan.bold nscan} to find vulnerable computers with known exploits.

      Start scanning, see what you can find.

      - X
    tasks:
      - { run: nscan }
  exploitable:
    text: |
      Hey, You found your first exploitable server. Congrats!

      No, seriously... Be proud, most people don't make it this far!

      At any time you can view all the servers under your control
      by running the command:

        $ {bold.cyan cat ~/servers}

      It's time to get paid. So start learning about crypto-currencies.

      - X
    tasks:
      - { train: crypto-01 }
  xssh:
    text: |
      Hacking servers and getting paid. This is our bread and butter.

      Hack one of your servers.

        $ {cyan.bold pkg install xssh}
        $ {cyan.bold cat ~/servers}
        $ {cyan.bold xssh <server>}

      Install the {cyan.bold coind} daemon and start it and get out.

        $ {cyan.bold pkg install coind}
        $ {cyan.bold coind start}
        $ {cyan.bold exit}

      - X
  wallet:
    text: |+
      Install a {cyan.bold wallet} to hold your {cyan.bold coin}.

      Use the {cyan.bold wallet} to {cyan.bold collect} your {cyan.bold coin}
      and view your {cyan.bold balance}.

        $ {cyan.bold pkg install wallet}
        $ {cyan.bold wallet collect}
        $ {cyan.bold wallet balance}

      - X
  cryptolock:
    text: |
      Running crypto miners is just one of many way to make money in this world.

      If you want to make real money, you're gonna have to do some dirt.

      Keep training until you have learned {cyan.bold Applied Cryptography}.

      Then I'll walk you through your first ransom.

      - X
    tasks:
      - { train: crypto-02 }
  ransom:
    text: |
      Users never back up their computers. If they did, it'd be bad news for us.

      Fortunately, their stupidity is easily exploitable.

      Scan for a Personal Computer, then {cyan.bold cryptolock} it.

      - X
    tasks:
      - { run: nscan pc }
      - { run: cryptolock }
coins:
  reward: 0.1
serverTypes:
  0: unknown
  1: iot
  2: pc
packages:
  nscan:
    require: ['training:scan-01']
    home: true
    remote: false
    scan-time: 7200 # 2 hours
  cryptolock:
    require: ['training:crypto-02']
    home: false
    remote: true
    bounty: 2
  xssh:
    require: []
    home: true
    remote: false
  coind:
    require: ['training:crypto-01']
    home: true
    remote: true
  wallet:
    require: ['training:crypto-01']
    home: true
    remote: false
    cooldown: 14400 # 4 hours
